-- Auto-generated by scripts/generate-archetype-seed.ts
-- Source: src/data/archetypes.ts
-- Re-run after editing the source file. Idempotent.
--
-- Apply with: npx wrangler d1 execute socialai-db --file=workers/api/seed_v7_archetypes.sql --remote

BEGIN TRANSACTION;

-- food-restaurant — Food, Café & Restaurant
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'food-restaurant',
  'Food, Café & Restaurant',
  'Bricks-and-mortar food businesses — cafés, bakeries, restaurants, takeaways, delis, food trucks, butchers. Customers physically visit or order for pickup/delivery. Imagery is the product itself plus the venue atmosphere. Voice is warm, sensory, locally rooted.',
  '["restaurant","cafe","café","bakery","deli","food truck","takeaway","pizza","grill","kitchen","bistro","sushi","burger","chicken","seafood","steak","pickle","ferment","artisan food","breakfast","brunch","lunch","catering"]',
  '["sourdough loaf cross-section on marble counter, morning window light","flat white coffee with latte art on rustic wooden table, top-down","croissants stacked in wicker basket, soft golden bakery light","overhead flatlay of breakfast spread: coffee, pastries, jam, butter","pastry display case interior, warm lighting, bakery atmosphere","cross-section of kimchi in a glass jar showing texture, side angle","sandwich loaded with deli meat and pickles, overhead on butcher paper","cafe storefront at golden hour, candid streetscape, no customers visible"]',
  'NEVER include people, faces, hands, owners, customers, or staff. NEVER render menus, price boards, or text overlays. Focus on the food itself, the venue interior, or candid empty-table moments.',
  'Warm, sensory, locally rooted. Name specific dishes and ingredients. Call out opening hours, pickup-only / delivery-area facts. Use Aussie casual contractions where appropriate.',
  '["Product Showcase","Behind the Bake","Customer Favourites","Tips & Pairings","Seasonal Specials"]',
  NULL
);

-- bbq-smokehouse — BBQ, Smokehouse & Grill
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'bbq-smokehouse',
  'BBQ, Smokehouse & Grill',
  'Specialty BBQ / smokehouse / grill businesses — competition pitmasters, BBQ catering, smokehouse restaurants, food trucks specialising in smoked meats. Distinct from generic restaurants because the craft (smoke, slow-cooking) IS the marketing.',
  '["bbq","barbeque","barbecue","smokehouse","pitmaster","smoked meats","low and slow","brisket","pulled pork","ribs"]',
  '["sliced smoked brisket fanned on butcher paper, golden hour light","pulled pork burger with coleslaw and pickles, close-up macro","BBQ ribs glistening with glaze on cedar plank, smoke wisps in background","food truck exterior at dusk with warm window light and queue area (empty)","overhead flatlay: brisket, slaw, beans, white bread on red checkered paper","smoker opened showing meat in atmospheric smoke, late afternoon sun, no person visible","wood pile next to the smoker, golden hour, candid working-yard texture"]',
  'NEVER include people, pitmasters, or customers. NEVER render menu boards or text overlays. Focus on the meat, smoke, fire, and the rig.',
  'Confident, no-frills, Aussie smoker culture. Name cuts, woods, cook times. References competition circuit or low-and-slow philosophy land well.',
  '["Cook of the Day","Smoke Science","Competition / Event Run","Customer Favourites","Behind the Pit"]',
  NULL
);

-- butcher-meat — Butcher & Specialty Meat
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'butcher-meat',
  'Butcher & Specialty Meat',
  'Butcher shops, specialty meat retailers, dry-age operations, charcuterie makers. Sells raw / prepared meats by weight or piece. Customer base is home cooks and chefs.',
  '["butcher","meat","charcuterie","dry age","dry-age","salumi","biltong","jerky","sausages"]',
  '["raw beef ribeye steak on dark wooden cutting board, warm lighting, overhead shot","rack of lamb on butcher paper with rosemary sprigs, natural side light","glass display case of fresh sausages and cuts, shop interior, soft daylight","aged dry-rubbed brisket close-up showing bark texture, dramatic lighting","butcher''s marble counter with herbs and twine, overhead flatlay","cast iron pan with thick pork chop and garlic, moody warm light, no person","hanging charcuterie in a dim curing room, atmospheric still life"]',
  'NEVER include people, hands handling meat, or staff. NEVER render hygiene-rule text or weights/prices. Focus on cuts, marbling, the venue.',
  'Knowledgeable, direct, ingredient-led. Name breeds, cuts, ageing periods. Speak to home cooks who care about provenance.',
  '["Cut of the Week","Provenance Story","Cooking Tips","Order Window","Seasonal Specials"]',
  NULL
);

-- agriculture-farming — Agriculture & Farming
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'agriculture-farming',
  'Agriculture & Farming',
  'Farms, vineyards, orchards, nurseries, livestock producers. Sells produce direct or wholesale. Imagery is land, animals, harvest. Voice is rooted in seasons and weather.',
  '["farm","agriculture","agri","livestock","dairy","crop","harvest","vineyard","orchard","nursery","horticulture","paddock","pastured","organic farm"]',
  '["rolling green paddock at golden hour with scattered trees, wide landscape","overhead flatlay of seasonal produce on a wooden crate with hessian","rows of grapevines in early morning fog, atmospheric vineyard shot","close-up macro of a fresh tomato cluster on the vine, water droplets","farm shed at dusk with warm window light, candid working-property texture","tractor in a freshly ploughed field, golden hour, no driver visible","overhead aerial of crop rows with shadow lines, abstract composition"]',
  'NEVER include farmers, workers, or staff. NEVER render machinery brand logos. Focus on land, animals, produce, and weather.',
  'Seasonal, weather-aware, grounded. Reference paddock rotation, harvest timing, breed/variety names. Plain-spoken; assume the reader respects the work.',
  '["Harvest Update","Animal of the Week","Behind the Gate","Seasonal Tips","Direct-Sale Window"]',
  NULL
);

-- tech-saas-agency — Tech, SaaS & Marketing Agency
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'tech-saas-agency',
  'Tech, SaaS & Marketing Agency',
  'Software products, marketing/social/creative agencies, IT consultancies, web designers, automation services, AI tools. Sells digital services or subscriptions. NO physical venue. Risk: AI defaults to SaaS-marketing tropes ("Ready to automate?", "Scale without scaling"); voice and imagery need active anchoring to the specific tool/service.',
  '["saas","software","tech","agency","marketing agency","social media agency","social media studio","creative studio","creative agency","web design","web designer","digital agency","consultancy","consulting","automation","it services","i.t.","ai tools","platform"]',
  '["matte black smartphone face-down on marble surface beside espresso cup, top-down, morning light","mechanical keyboard with backlit keys on a dark moody desk, candid close-up, no person","rack of glowing server hardware, abstract tech atmosphere, neon accents","aerial view of clean desk with notebook, pen, plant and closed laptop, beige aesthetic","coffee shop counter scene with laptop, latte and notebook, warm afternoon light, no person","creative wall of post-it notes in a bright office, daylight from window, candid texture","multi-screen agency desk with calendar view glowing softly, late evening, no person","whiteboard wall with kanban sticky-notes, daylight, creative studio atmosphere","abstract close-up of glowing fibre cables in dark room, blue+orange contrast","home office windowsill with plant, mug and a closed notebook at sunrise"]',
  'NEVER render UI mockups, dashboards, pricing tables, app screenshots, wireframes, or marketing graphics — these defeat the entire point of using FLUX (use real screenshots if you need UI). NEVER include people typing or "founders at whiteboard" — even hands break the aesthetic.',
  'Specific. Name the actual tool, the actual integration, the actual feature. Resist the urge to say "transform your business" — say what your tool does in the next 30 seconds. Pricing should be concrete, not "from competitive rates".',
  '["Feature Showcase","Workflow Tutorial","Customer Story (verified)","Behind the Build","Industry Take"]',
  '["thought leadership","paradigm shift","mission-critical","enterprise-grade","best-in-class","world-class","cutting-edge","turnkey","end-to-end","frictionless","seamless integration","value proposition"]'
);

-- professional-services — Professional Services
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'professional-services',
  'Professional Services',
  'Accountants, lawyers, financial advisors, architects, engineers, consultants. Client-by-client trust-based service businesses with formal credentials. Distinct from tech-agency: regulated, slower-moving, conservative.',
  '["accountant","accounting","lawyer","legal","solicitor","barrister","financial advisor","financial planner","architect","engineer","engineering firm","tax","audit","mortgage broker"]',
  '["leather-bound desk diary and fountain pen on a wooden desk, professional atmosphere","shelf of legal books with reading light, library-style interior","aerial view of meeting table with notepads and coffee cups, no people","architectural blueprint on a desk with scale ruler, drafting close-up","professional building exterior at golden hour, candid streetscape","window office at twilight with city lights visible, calm atmosphere"]',
  'NEVER include people, suits, or handshakes — the cliché stock-photo aesthetic. Focus on tools-of-trade, considered interiors, and material details.',
  'Considered, precise, jargon-aware. Cite frameworks, regulatory bodies, and case-specific advice without crossing into general guidance. Plain-language explanations land best.',
  '["Regulatory Update","Client FAQ","Case Study (anonymised)","Tax/Compliance Calendar","Industry Commentary"]',
  NULL
);

-- retail-ecommerce — Retail & E-commerce
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'retail-ecommerce',
  'Retail & E-commerce',
  'Bricks-and-mortar retail, e-commerce stores, boutiques, fashion, gift shops, florists, homewares. Sells products by the unit. Imagery is the product on display, often styled flatlay.',
  '["retail","shop","store","boutique","ecommerce","e-commerce","fashion","clothing","gift","homewares","florist","flowers","lifestyle store"]',
  '["overhead flatlay of products on linen with herbs and props, magazine styling","boutique storefront with window display, warm interior light, candid streetscape","single hero product on textured background, soft directional lighting","open shelving styled with the product range, retail interior","gift-wrapped product on a textured surface with ribbon detail, close-up","floral arrangement on a marble counter, soft natural light"]',
  'NEVER include people, hands modelling products, or shop assistants. NEVER render price tags or sale signs. Focus on the product itself, styled.',
  'Style-led, specific (call out colourway, size, materials). Reference current collection, limited run, sourcing story. Cash-and-collect / shipping facts important.',
  '["New Arrival","Styled Outfit / Display","Behind the Source","Customer Wears (no faces)","Sale / Limited Run"]',
  NULL
);

-- health-wellness — Health & Wellness
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'health-wellness',
  'Health & Wellness',
  'Gyms, yoga studios, pilates, beauty salons, spas, massage therapists, physios, chiros. Service-based, body-focused, often subscription/booking model. Imagery is space + tools, NEVER bodies.',
  '["gym","fitness","pilates","personal trainer","beauty","salon","spa","massage","physio","chiro","wellness","health","dental","medical","osteo"]',
  '["meditation cushion in sunlit room with linen curtains, calm atmosphere","overhead flatlay of journal, herbal tea, and dried flowers, wellness aesthetic","rolled yoga mat on polished wood floor, soft window light","minimal treatment room interior with linen and timber, peaceful atmosphere","fitness equipment in modern gym at dawn, candid empty space","close-up of hands holding warm ceramic mug, cozy lighting (hands acceptable for tea/treatment shots)"]',
  'NEVER include people exercising, in treatment, or in poses. NEVER render before/after comparison shots. Focus on calm space, ritual tools, daylight.',
  'Grounded, body-respectful, non-prescriptive. Avoid medical claims unless registered. Reference movement, breath, recovery rituals.',
  '["Move of the Week","Recovery Tips","Class Schedule","Member Story (anonymised)","Studio Update"]',
  NULL
);

-- wellness-mindfulness — Mindfulness & Breathwork
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'wellness-mindfulness',
  'Mindfulness & Breathwork',
  'Specialty wellness practices — meditation teachers, breathwork facilitators, sound healing, holistic coaching. Distinct from gyms/spas because the offering is contemplative practice, not physical training.',
  '["meditation","mindful","mindfulness","breathwork","sound healing","holistic","reiki","energy work","yoga teacher"]',
  '["serene candle on stone with soft window light, minimal composition","misty forest path at dawn, atmospheric grounding nature shot","overhead flatlay of crystals, journal, and dried sage, intentional arrangement","sound bowl on linen at golden hour, close-up macro","meditation cushion stack in a sunlit room, peaceful empty space","forest floor close-up with moss and fern, grounding texture"]',
  'NEVER include people in poses or in session. Focus on space, light, and contemplative objects.',
  'Reflective, unhurried, somatic vocabulary. Avoid "transformation" cliché. Reference specific practices and their effects.',
  '["Practice Invitation","Reflection / Quote","Workshop Announcement","Behind the Practice","Seasonal Ritual"]',
  NULL
);

-- automotive-mechanic — Automotive & Mechanic
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'automotive-mechanic',
  'Automotive & Mechanic',
  'Mechanic workshops, auto detailers, restorers, panel beaters, tyre shops, performance / custom builders. Hands-on craft business with workshop aesthetic.',
  '["mechanic","garage","auto","automotive","workshop","panel beater","tyre","tire","detailer","restoration","performance","car repair"]',
  '["classic car in garage bay under work lights, atmospheric","mechanic''s tool wall with organised wrenches, industrial light","engine bay close-up with chrome detail, shallow focus","oil-stained workbench with vintage tools, candid texture","detailed leather steering wheel close-up after restoration","workshop exterior with vintage signage, golden hour","rolling tool chest in a clean workshop bay, side light"]',
  'NEVER include mechanics, hands on the spanner, or customer cars with plates visible. Focus on the cars, the tools, the workshop atmosphere.',
  'Practical, no-nonsense, model-specific. Call out make/model/year. Reference parts, services, turnaround times. Aussie tradie-aware.',
  '["Job of the Week","Restoration Progress","Workshop Tips","Customer Build","Service Reminder"]',
  NULL
);

-- outdoor-sports — Outdoor & Sports
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'outdoor-sports',
  'Outdoor & Sports',
  'Surf shops, climbing gyms, dive operators, outdoor gear retailers, sports schools. Lifestyle-driven, environmentally aware, gear-focused.',
  '["surf","surf shop","dive","diving","climb","climbing","outdoor","adventure","sports","gear","hiking","camping","fishing","kayak"]',
  '["surfboard standing upright in sand with ocean background, golden hour","row of surfboards in shop rack, natural daylight from window","wave breaking with empty horizon, dramatic backlight","overhead flatlay of beach gear: board wax, sunscreen, towel, sandals","aerial shot of empty surf break at dawn, dramatic clouds","wetsuit hanging on weathered wooden fence, salty atmosphere","climbing chalk bag and shoes on rock, candid gear shot"]',
  'NEVER include athletes, surfers, or customers using the gear. Focus on the gear itself, the environment, and conditions.',
  'Conditions-aware (swell, wind, tide, weather). Gear-specific (model, size, fit). Aussie-coastal where applicable.',
  '["Conditions Report","Gear Pick","Trip Recap (no faces)","Tip / Skill","Local Spot Profile"]',
  NULL
);

-- creative-arts — Creative Arts & Handmade
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'creative-arts',
  'Creative Arts & Handmade',
  'Jewellers, ceramicists, leatherworkers, makers, illustrators, painters selling original work. Distinct from retail because the craft IS the product story.',
  '["jewel","jewellery","jewelry","ceramicist","pottery","leather","maker","handmade","artist","illustrator","painter","craftsperson","artisan"]',
  '["single ring on velvet pad with soft directional lighting","overhead flatlay of necklaces fanned on linen background","close-up macro of gemstone showing facets and light play","workbench with tools and an in-progress piece, atmospheric warm light","jewellery in display case with reflections, boutique interior","open jewellery box with multiple pieces, overhead, soft shadows","potters wheel with clay form, candid studio shot, no hands visible"]',
  'NEVER include the maker, hands at work, or customers wearing pieces. Focus on the work itself, the workshop, the materials.',
  'Material-led, process-aware. Reference the actual materials, the technique, the time investment. Custom-order language welcomed.',
  '["Piece of the Week","In-Progress (no hands)","Material Story","Custom Commission Window","Studio Update"]',
  NULL
);

-- events-festivals — Events & Festivals
INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (
  'events-festivals',
  'Events & Festivals',
  'Festival organisers, event venues, conferences, markets, expos, weddings. Time-bounded events with a build-up cadence (announcement → countdown → on-day → recap).',
  '["festival","event","conference","market","expo","show","concert","fair","wedding","venue"]',
  '["outdoor festival ground at dusk with festoon lights and empty stage, atmospheric","competition trophies and ribbons on draped table, dramatic spotlight","overhead aerial of festival grounds with marquees, no crowds","festival entrance gate with banners, golden hour, anticipation feel","venue interior set for an event with empty chairs and stage, warm light","flatlay of event programme, lanyard, and pen on wood, behind-the-scenes"]',
  'NEVER include attendees, performers, or crowds — privacy + photo-release issues at scale. Focus on the venue, the set-up, the lead-up details.',
  'Countdown-aware. Practical (dates, gates, tickets, weather). Build anticipation without hype. Aftermath recaps focus on numbers + thanks, not "epic vibes".',
  '["Save the Date","Programme Reveal","Behind the Build","Day-of Logistics","Recap & Thanks"]',
  NULL
);

COMMIT;

-- Seeded 13 archetypes.
