/**
 * Generates the SQL seed file for the `business_archetypes` D1 table.
 *
 * Run with: `npx tsx scripts/generate-archetype-seed.ts > workers/api/seed_v7_archetypes.sql`
 *
 * Source of truth is src/data/archetypes.ts. Re-run this script after editing
 * that file to refresh the seed. Idempotent — uses `INSERT OR REPLACE` so
 * running the seed multiple times leaves the table in the same state.
 */

import { ARCHETYPES } from '../src/data/archetypes';

const sqlEscape = (s: string) => s.replace(/'/g, "''");

console.log('-- Auto-generated by scripts/generate-archetype-seed.ts');
console.log('-- Source: src/data/archetypes.ts');
console.log('-- Re-run after editing the source file. Idempotent.');
console.log('--');
console.log('-- Apply with: npx wrangler d1 execute socialai-db --file=workers/api/seed_v7_archetypes.sql --remote');
console.log('--');
console.log('-- No BEGIN/COMMIT — D1\'s remote executor rejects BEGIN TRANSACTION/SAVEPOINT');
console.log('-- (it wraps each statement in its own transaction internally). The INSERT OR');
console.log('-- REPLACE statements below are idempotent on their own.');
console.log('');

for (const a of ARCHETYPES) {
  console.log(`-- ${a.slug} — ${a.name}`);
  console.log(`INSERT OR REPLACE INTO business_archetypes (slug, name, description, keywords, image_examples, image_avoid_notes, voice_cues, content_pillars, banned_trope_extras) VALUES (`);
  console.log(`  '${sqlEscape(a.slug)}',`);
  console.log(`  '${sqlEscape(a.name)}',`);
  console.log(`  '${sqlEscape(a.description)}',`);
  console.log(`  '${sqlEscape(JSON.stringify(a.keywords))}',`);
  console.log(`  '${sqlEscape(JSON.stringify(a.imageExamples))}',`);
  console.log(`  '${sqlEscape(a.imageAvoidNotes)}',`);
  console.log(`  '${sqlEscape(a.voiceCues)}',`);
  console.log(`  '${sqlEscape(JSON.stringify(a.contentPillars))}',`);
  console.log(`  ${a.bannedTropeExtras ? `'${sqlEscape(JSON.stringify(a.bannedTropeExtras))}'` : 'NULL'}`);
  console.log(`);`);
  console.log('');
}

console.log(`-- Seeded ${ARCHETYPES.length} archetypes.`);
